# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: 
     name: 'Homelabpool'
    # pool:
    #   vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'homelabregistry'
        repository: '0908887875/netcore6'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
